### ISSUE TITLE
How to contribute

### ISSUE THREAD

**Issue by dahlbaek** [laysakura/beam#1]
Coming from https://github.com/apache/beam/issues/21089#issuecomment-1499443923, I noticed that you (@laysakura) welcome contributions! I'm interested in contributing, but wondering how you would prefer to handle contributions.

Do you already have plans regarding the direction/priorities, or should I just go hunting for todos in the code that seem like something I could work on? Would you like an issue created first, or rather not be bothered until (I think) I have something ready for review?

**Comment by laysakura** [comment]
Hi @dahlbaek ! I'm pretty happy to receive your help.

I created some issues to resolve soon. If you are interested in some of them, please assign them to yourself.

Also, as you already noticed, there are many TODO comments in the rust codebase. I prefer to have issues first and then to create pull request but I don't mind so much if you start from creating a pull request.

**Comment by dahlbaek** [comment]
Sounds good! I had a brief look at #3, but I don't think I have permission to assign issues 🤔

**Comment by laysakura** [comment]
> I have permission to assign issues 🤔

Oh, sorry. I'll check the permission settings.

**Comment by laysakura** [comment]
@dahlbaek I sent an invitation to make you as a collaborator of this repository.

**Comment by laysakura** [comment]
@dahlbaek Thank you so much for the #7 .

Would you be interested in working on any of the existing issues? I am planning to start working on #4 or #6 from Monday (JST). If you have a preference or interest in either of them, please let me know, and I will assign it to you.

**Comment by dahlbaek** [comment]
Thank you for the opportunity to collaborate!

I would be very interested in #4. However, I should say that I mostly have time available during the weekends, so depending on how much work is needed it might take me some time to prepare a PR. Let me know if you want to move quick on this, in which case it might not be a good idea to assign it to me...

**Comment by laysakura** [comment]
Hey @dahlbaek, I think you're the best person to tackle #4 from #7 and https://github.com/laysakura/beam/issues/4#issuecomment-1501012735.

I'm planning to give a presentation about the Beam Rust SDK at [Beam Summit 2023](https://beamsummit.org/), which is happening on June 13th. Of course, I'll make sure to acknowledge your contributions during the presentation! It would be awesome if we could get **#4 done by April**.

Here's what I'm thinking:

- I'll start by working on #6 to gain a better understanding of the entire interface.
  - I'd love to hear your thoughts on this if you have the time.
- @dahlbaek can start working on #4.

What do you think of this plan?

**Comment by dahlbaek** [comment]
Sounds great!

**Comment by brucearctor** [comment]
See you in NY - @laysakura !

**Comment by laysakura** [comment]
I'm waiting for @sjvanrossum to create issues related to:

- https://github.com/laysakura/beam/pull/14#issuecomment-1519277396
- https://github.com/laysakura/beam/pull/14#issuecomment-1519905191

I'll also create an issue or a design doc related to:

- statically-typed pipeline only for SDK described in: https://github.com/laysakura/beam/pull/14#issuecomment-1519580390

**Comment by laysakura** [comment]
@dahlbaek Thank you for your consistent contributions! Would you be interested in continuing with the following task?

https://github.com/laysakura/beam/pull/14#issuecomment-1518941241
> My opinion is that we should first aim for putting something together that can run in a distributed manner.

**Comment by dahlbaek** [comment]
Definitely! I'll have to look around a bit to figure out exactly what's missing and where to start 🤔 feel free to make suggestions if you already have a good feel for it!

**Comment by laysakura** [comment]
@dahlbaek In my opinion, Rust-specific components are located in two main areas:

1. API in SDK
  - closely related to the [Programming Guide](https://beam.apache.org/documentation/programming-guide)
2. Language-specific SDK harness
  - documented in [Apache Beam Fn API Overview](https://docs.google.com/document/d/1XYzb1Fnt2sam7u2MsGFaZp-2qSIGxUn66VLer-bcXAk/edit#heading=h.p6lvszfbmyj6)

      ![image](https://user-images.githubusercontent.com/498788/234443597-98474be1-f0c9-4813-8e03-15888a6a8ec9.png)

Although I started with and am continuing to work on 1. (for example, #9), I believe that 2. is more important in determining the types and traits required for distributed runtimes a distributed manner.

Therefore, my suggestion is as follows:

- Read the documents related to the Fn API and SDK harness listed in the [Design Documents](https://cwiki.apache.org/confluence/display/BEAM/Design+Documents) section.
- Look at other languages' implementations related to the Fn API and SDK harness.
- Perhaps write a design document for Rust's Fn API and SDK harness, although we may be able to skip this step if things are not too complicated.
- Write an initial SDK harness that works as a Docker container.

This may be a long journey, but we are happy to help you along the way!

**Comment by Kelvinyu1117** [comment]
Hi all, I'm also coming from the same issue on `apache/beam` and I'm interested in contributing to this project. Which issue is good for me to kickstart?

**Comment by laysakura** [comment]
@Kelvinyu1117 I appreciate your participance! How about:

- https://github.com/laysakura/beam/issues/34
- https://github.com/laysakura/beam/issues/8

**Comment by laysakura** [comment]
We have created communication channels (Discord and design docs).
See [the README](https://github.com/laysakura/beam/tree/rust_sdk/sdks/rust#beam-rust-sdk-experimental).

We are waiting for your contribution!

**Comment by brucearctor** [comment]
Great, @laysakura !   Thanks for keeping this moving, and see you at next beam summit [will make a point to connect in person that time :-) ]

**Comment by laysakura** [comment]
@brucearctor It definitely was great memory in my life! I appreciate all the help from community members, including you.

For those who have interests in my talk, I'll quickly share [my slides](https://docs.google.com/presentation/d/1FUmr1B5vJWUFM9kLEKsBcYQpJzRqP-LQKn7j3GXgT6E/edit#slide=id.g24be81ab6eb_0_10).
(I guess the recording will be available about a month later).
